landing/controllers/BusinessPlanController.php
<?php

namespace landing\controllers;

use common\modules\tenant\models\Tenant;
use landing\models\Lead;
use lead\Module;
use Yii;
use yii\web\Controller;

use landing\models\BusinessPlan;
use common\components\gearman\Gearman;

class BusinessPlanController extends Controller
{
    public function actionSend()
    {
        if (!Yii::$app->request->isAjax) {
            return false;
        }
        app()->response->format = \yii\web\Response::FORMAT_JSON;


        $model = new BusinessPlan();

        if ($model->load(app()->request->post())) {
            if ($model->validate()) {
                $model->sendEmail();
                $tenant = $model->getTenant();
                if (!is_null($tenant)) {
                    $model->is_registered = 1;
                }

                if (YII_ENV_PROD && $model->isNeedCreateLead()) {
                    $this->createLead(
                        $model->name,
                        empty($tenant) ? null : $tenant->tenant_id,
                        empty($tenant) ? null : $tenant->domain,
                        $model->phone,
                        $model->email,
                        $model->ip
                    );
                }

                $model->save();

                return ['status' => 'success'];
            }

            return ['status' => 'error'];
        }
    }

    /**
     * Create lead
     *
     * @param string $name
     * @param int    $tenantId
     * @param string $domain
     * @param string $phone
     * @param string $email
     *
     * @throws \yii\base\InvalidConfigException
     */
    private function createLead($name, $tenantId, $domain, $phone, $email, $ip)
    {
        /* @var $lead Lead */
        $lead = \Yii::createObject(Lead::className());
        $url  = empty($domain) ? '' : Tenant::getTenantUrl($domain);

        $lead->createLead(null, $name, null, $tenantId, $url, $phone, $email, $ip, Module::SOURCE_BUSINESS_PLAN);
    }

    public function actionTest()
    {
    }


    /**
     * Ajax signup validation
     * @return json
     */
    public function actionValidate()
    {
        if (Yii::$app->request->isAjax) {
            $model = new BusinessPlan;
            $model->load(post());
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            return \yii\widgets\ActiveForm::validate($model);
        }
    }

    public function actionSendSmsCode($phone)
    {
        if (!Yii::$app->request->isAjax) {
            return false;
        }

        $test = !YII_ENV_PROD && $phone == '79001234567';

        if (!$test) {
            $data['server']  = \common\models\AdminSmsServer::find()->asArray()->where('active=1')->all();
            $data['phone']   = $phone;
            $data['text']    = rand(1000, 9999);
            $data['expires'] = time() + app()->params['sms_code_exp'];
        } else {
            $data['text'] = 4785;
        }

        $session              = session();
        $session['sms_code']  = $data['text'];
        $session['sms_phone'] = $phone;
        $session['sms_exp']   = time() + app()->params['sms_code_exp'];

        if (!$test) {
            Yii::$app->gearman->doBackground(Gearman::SMS_TASK, $data);
        }
    }

    /**
     * Tenant confirm phone
     */
    public function actionConfirmSmsCode($code)
    {
        if (!Yii::$app->request->isAjax) {
            return false;
        }

        $result = ['error' => null];

        if (!(session()->get('sms_code') == $code && $this->checkSmsCodeExpire())) {
            $result['error'] = t('validator', 'Invalid sms code');
        }

        return json_encode($result);
    }

    /**
     * Check expire sms code
     */
    protected function checkSmsCodeExpire()
    {
        return session()->get('sms_exp') > time();
    }
}

landing/controllers/SiteController.php
<?php

namespace landing\controllers;

use app\components\actions\CaptchaAction;
use common\components\gearman\Gearman;
use landing\components\actions\ErrorAction;
use landing\models\Conversion;
use landing\models\Docpack;
use landing\models\LoginForm;
use landing\models\Presentation;
use landing\modules\community\models\user\CommunityLoginForm;
use landing\modules\community\models\user\CommunityUser;
use landing\modules\community\models\user\ConfirmEmailForm;
use landing\modules\community\models\user\PasswordResetRequestForm;
use landing\modules\community\models\user\ResetPasswordForm;
use landing\modules\community\models\user\SignupForm;
use Yii;
use yii\redis\Connection;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

class SiteController extends \yii\web\Controller
{

    const COUNTER_SIGNUPS = 'counter signups';
    const COUNTER_LOGINS = 'counter logins';
    const COUNTER_COMMUNITY_LOGINS = 'counter community logins';
    const MAX_ATTEMPTS = 5;

    public $showMenu = true;

    public function actions()
    {
        return [
            'error'   => ErrorAction::className(),
            'captcha' => [
                'class'           => CaptchaAction::className(),
                'foreColor'       => 0xFF8B0F,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only'  => ['community-logout', 'community-signup'],
                'rules' => [
                    [
                        'actions' => ['community-signup'],
                        'allow'   => true,
                        'roles'   => ['?'],
                    ],
                    [
                        'actions' => ['community-logout'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => \yii\filters\VerbFilter::className(),
                'actions' => [
                    'community-logout'  => ['post'],
                    'create-conversion' => ['post'],
                    'send-presentation' => ['post'],
                ],
            ],
        ];
    }



    public function actionContactForm()
    {
        if (!Yii::$app->request->isAjax) {
            return false;
        }

        $json = 0;

        if (isset($_POST['Contact'])) {
            $params = [
                'TEMPLATE' => 'contactForm',
                'TO'       => app()->params['contacts.email'],
                'SUBJECT'  => 'Сообщение с формы обратной связи сайта ' . app()->name,
                'DATA'     => [
                    'NAME'     => $_POST['Contact']['name'],
                    'PHONE'    => $_POST['Contact']['phone'],
                    'EMAIL'    => $_POST['Contact']['email'],
                    'MESSAGE'  => $_POST['Contact']['message'],
                    'LANGUAGE' => app()->language,
                ],
            ];

            sendMail($params);
            $json = 1;
        }

        return json_encode($json);
    }

    public function actionLogin()
    {
        if (!Yii::$app->request->isAjax) {
            throw new NotFoundHttpException();
        }

        app()->response->format = \yii\web\Response::FORMAT_JSON;

//        if (!app()->user->isGuest) {
//            return 'success';
//        }

        $scenario = LoginForm::SCENARIO_DEFAULT;

        $counter = session()->get(self::COUNTER_LOGINS);
        if ($counter >= self::MAX_ATTEMPTS) {
            $scenario = LoginForm::SCENARIO_CAPTCHA;
        }

        $model = new LoginForm([
            'scenario' => $scenario,
        ]);

        if ($model->load(app()->request->post())) {
            if ($model->validate()) {

                $gootaxUser    = $model->getUser();
                $communityUser = CommunityUser::find()
                    ->where([
                        'user_id' => $gootaxUser->user_id,
                        'status'  => CommunityUser::STATUS_ACTIVE,
                    ])->one();

                if (!$communityUser) {
                    //$communityUser = \landing\components\SynchManager::registerGootaxClient($gootaxUser);

                    $communityUser = SignupForm::signupFromGootax($gootaxUser);
                }

                if (!$communityUser || !app()->user->login($communityUser)) {
                    session()->setFlash('error', 'Ошибка входа, cообщите администратору.');
                }

                return 'success';
            } else {
                $errors = $model->getFormattedError();

                if ($counter >= self::MAX_ATTEMPTS - 1) {
                    $errors['showCaptcha'] = true;
                }
                session()->set(self::COUNTER_LOGINS, (++$counter));

                return $errors;
            }
        }
    }

    public function actionRecoveryPassword()
    {
        app()->response->format = \yii\web\Response::FORMAT_JSON;

        $model = new \landing\models\PasswordResetRequestForm;

        if ($model->load(app()->request->post())) {
            if ($model->validate()) {
                if ($model->sendEmail()) {
                    $message = 'На Ваш email отправлены инструкции по восстановлению пароля.';
                } else {
                    $message = 'Возникла ошибка при отправке письма на Ваш email.';
                }
                app()->session->setFlash('success', $message);

                return 'success';
            }
        }

        app()->response->format = \yii\web\Response::FORMAT_JSON;

        return ActiveForm::validate($model);
    }

    public function actionDeleteCache()
    {
        $cache = app()->cache;
        echo $cache->flush() ? 'Good' : 'Error';
    }

    public function actionCommunitySignup()
    {
        app()->response->format = \yii\web\Response::FORMAT_JSON;

        $scenario = SignupForm::SCENARIO_DEFAULT;

        $counter = session()->get(self::COUNTER_SIGNUPS);
        if ($counter >= self::MAX_ATTEMPTS) {
            $scenario = SignupForm::SCENARIO_CAPTCHA;
        }

        $model = new SignupForm([
            'scenario' => $scenario,
        ]);

        if ($model->load(app()->request->post())) {
            if ($model->signup()) {

                app()->session->setFlash('success', 'На Ваш email отправленно письмо подтверждения регистрации.');

                return 'success';
            } else {
                $errors = $model->getFormattedError();

                if ($counter >= self::MAX_ATTEMPTS - 1) {
                    $errors['showCaptcha'] = true;
                }
                session()->set(self::COUNTER_SIGNUPS, (++$counter));

                return $errors;
            }
        }
    }

    public function actionGotoGootax()
    {
        $user = \landing\models\User::findone(user()->user_id);

        $user->generateAuthKey();
        $user->auth_exp = time() + \landing\models\LoginForm::AUTH_EXP;
        $user->save(false, ['auth_key', 'auth_exp']);

        $this->redirect(
            app()->params['site.protocol'] . '://' . $user->tenant->domain . '.' . app()->params['site.domain'] . '/tenant/user/cross-login?auth_key=' . $user->auth_key . '&user_id=' . $user->user_id);
    }

    public function actionCommunityLogin()
    {
        if (!Yii::$app->request->isAjax) {
            throw new NotFoundHttpException();
        }

        if (!app()->user->isGuest) {
            return $this->goHome();
        }

        app()->response->format = \yii\web\Response::FORMAT_JSON;

        $scenario = CommunityLoginForm::SCENARIO_DEFAULT;

        $counter = session()->get(self::COUNTER_COMMUNITY_LOGINS);
        if ($counter >= self::MAX_ATTEMPTS) {
            $scenario = CommunityLoginForm::SCENARIO_CAPTCHA;
        }

        $model = new CommunityLoginForm([
            'scenario' => $scenario,
        ]);

        if ($model->load(app()->request->post())) {
            if ($model->login()) {
                return 'success';
            } else {
                $errors = $model->getFormattedError();

                if ($counter >= self::MAX_ATTEMPTS - 1) {
                    $errors['showCaptcha'] = true;
                }
                app()->session->set(self::COUNTER_COMMUNITY_LOGINS, (++$counter));

                return $errors;
            }
        }
    }

    public function actionCommunityLogout()
    {
        app()->user->logout();
        $this->goHome();
    }

    public function actionCommunityConfirmEmail($token)
    {
        try {
            $model = new ConfirmEmailForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->confirmEmail()) {
            app()->session->setFlash('success', 'Ваш email успешно подтвержден.');
        } else {
            app()->session->setFlash('error', 'Ошибка подтверждения Вашего email.');
        }

        return $this->goHome();
    }

    public function actionCommunityRequestResetPassword()
    {
        app()->response->format = Response::FORMAT_JSON;

        $model = new PasswordResetRequestForm();

        if ($model->load(app()->request->post())) {
            if ($model->validate()) {
                if ($model->sendEmail()) {
                    $message = 'На Ваш email отправлены инструкции по восстановлению пароля.';
                } else {
                    $message = 'Возникла ошибка при отправке письма на Ваш email.';
                }
                app()->session->setFlash('success', $message);

                return 'success';
            }
        }

        return ActiveForm::validate($model);
    }

    public function actionCommunityResetPassword($token)
    {
        try {

landing/views/site/download-plan.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\views\site\assets\DownloadPlanAsset;

DownloadPlanAsset::register($this);

/* @var $model \landing\models\BusinessPlan */
/* @var $this \yii\web\View */

?>

<div style="display: none;">
    <div class="remodal dp_win" data-remodal-id="download_plan">
        <?php $form = \yii\widgets\ActiveForm::begin([
                'id'                     => 'download-plan-form',
                'action'                 => '/site/download-plan',
                'enableClientValidation' => false,
                'enableAjaxValidation'   => true,
                'validateOnSubmit'       => false,
                'validationUrl'          => \yii\helpers\Url::to('/business-plan/validate'),
                'errorCssClass'          => 'error',
                'fieldConfig'            => app()->params['fieldOptions'],
                'options'                => [
                    'data' => [
                        'google-analytics' => YII_ENV_PROD,
                        'yandex-metrika' => YII_ENV_PROD,
                    ],
                ],
        ]); ?>
        <button data-remodal-action="close" class="remodal-close"></button>
        <div id="download-plan-step1">
            <h2>Скачать бизнес-план</h2>
            <p>Заполните форму и мы отправим бизнес-план на вашу эл. почту.</p>
            <div class="lf_input">
                <?= $form->field($model, 'name')->textInput([
                    'maxLength'   => 255,
                    'placeholder' => $model->attributeLabels()['name'],
                ]); ?>
            </div>
            <div class="lf_input">
                <?= $form->field($model, 'email')->textInput([
                    'maxLength'   => 255,
                    'placeholder' => $model->attributeLabels()['email'],
                ]); ?>
            </div>
            <div class="lf_input">
                <?= $form->field($model, 'phone')->textInput([
                    'maxLength'   => 255,
                    'placeholder' => $model->attributeLabels()['phone'],
                    'class'       => 'mask_phone',
                    'options'     => [
                        'class' => 'mask_phone',
                    ],
                ]); ?>
            </div>
            <div class="lf_subm">
                <?= Html::submitInput('Далее',[
                        'class' => 'button',
                        'id'  => 'businessplan-submit',
                    ]); ?>
            </div>
        </div>

        <div id="download-plan-step2" class="reg_step_2" style="display: none">
            <h2>Подтвердите телефон</h2>
            <p>Введите код в SMS, который вам пришёл.</p>
            <div class="lf_input">
                <input id="download-plan-sms_code" name="sms_code" type="text" placeholder="Код в смс" value="" />
                <span class="er_text">Не заполнено</span>
            </div>
            <div class="reg_control">
                <a class="send_block" id="send_sms_again-download-plan" href="">Отправить заново</a>
                <a id="go_to_download-plan-step1" href="">Изменить данные</a>
            </div>
            <div class="lf_sub">
                <?= Html::submitInput('Подтвердить', ['class' => 'button']) ?>
            </div>
        </div>

        <div id="download-plan-step3" style="display: none">
            <div class="lf_success">
                <h2>Готово!</h2>
                <i></i>
                <p>Бизнес-план успешно отправлен на указанную вами электронную почту</p>
                <div class="lf_subm">
                    <?= Html::a('Узнайте о возможностях Гутакс',['/capabilities'],['class' => 'button']); ?>
                </div>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

landing/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>

<section class="top_page tp_support">
    <div class="content">
        <h1><?= Html::encode($message) . ' (' . $exception->statusCode . ')'?></h1>
        <p><?= t('error', 'The above error occurred while the Web server was processing your request.'); ?></p>
    </div>
</section>

landing/views/site/error404.php
<?php

use yii\helpers\Url;

?>

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Gootax</title>
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,400italic&subset=cyrillic' rel='stylesheet'
              type='text/css'>
        <link rel="stylesheet" href="/error/css/main.css"/>
    </head>
    <body>
    <div class="wrapper">
        <div class="error_text">
            <h1>:-(</h1>
            <div>
                <b><?= $name; ?></b><span><?= $message; ?></span>
                <h2><a href="<?= Url::to(['/']); ?>">Перейти на главную страницу Гутакса</a></h2>
            </div>
        </div>
    </div>
    </body>
</html>

landing/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\modules\user\models\LoginForm */

$this->title = 'Авторизация';
?>

<div class="form-box" id="login-box">
    <div class="header"><?= Html::encode($this->title) ?></div>
    <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
        <div class="body bg-gray">
            <?= $form->field($model, 'login') ?>
            <?= $form->field($model, 'password')->passwordInput() ?>
            <?= $form->field($model, 'rememberMe')->checkbox(['class'=>'simple']) ?>
        </div>
        <div class="footer">
            <?= Html::submitButton('Войти', ['class' => 'btn bg-olive btn-block', 'name' => 'login-button']) ?>
        </div>
    <?php ActiveForm::end(); ?>
</div>

landing/views/site/registerDistributer.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\views\site\assets\RegisterDistributerAsset;

/* @var $model \landing\models\RegisterDistributerForm */
/* @var $this \yii\web\View */

RegisterDistributerAsset::register($this);

?>

<div style="display: none">
    <div class="remodal rem_part" data-remodal-id="partner"
         data-remodal-options="hashTracking: false">
        <button data-remodal-action="close" class="remodal-close"></button>
        <div id="register-distributer-step1" style="display: block">
            <h2>Стать партнером</h2>
            <?php
            $form = \yii\widgets\ActiveForm::begin([
                    'id'                     => 'register-distributer-form',
                    'action'                 => '/site/register-distributer',
                    'enableClientValidation' => false,
                    'enableAjaxValidation'   => true,
                    'validateOnBlur'         => false,
                    'validateOnChange'       => false,
                    'errorCssClass'          => 'error',
                    'fieldConfig'            => app()->params['fieldOptions'],
                    'options'                => [
                        'data' => [
                            'google-analytics' => YII_ENV_PROD,
                        ],
                    ],
            ]);

            ?>

            <h5>Контактное лицо</h5>

            <?=
            $form->field($model, 'contact_fio')->textInput([
                'maxLength'   => 255,
                'placeholder' => $model->attributeLabels()['contact_fio'],
            ]);

            ?>

            <?=
            $form->field($model, 'contact_position')->textInput([
                'maxLength'   => 255,
                'placeholder' => $model->attributeLabels()['contact_position'],
            ]);

            ?>

            <?=
            $form->field($model, 'contact_phone')->textInput([
                'maxLength'   => 255,
                'placeholder' => $model->attributeLabels()['contact_phone'],
                'class'       => 'mask_phone',
                'options'     => [
                    'class' => 'mask_phone',
                ]
            ]);

            ?>

            <?=
            $form->field($model, 'contact_email')->textInput([
                'maxLength'   => 255,
                'placeholder' => $model->attributeLabels()['contact_email'],
            ]);

            ?>
            <hr class="small_hr">


            <h5>Компания</h5>
            <?=
            $form->field($model, 'company')->textInput([
                'maxLength'   => 255,
                'placeholder' => $model->attributeLabels()['company'],
            ]);

            ?>

            <?=
            $form->field($model, 'city')->textInput([
                'maxLength'   => 255,
                'placeholder' => $model->attributeLabels()['city'],
            ]);

            ?>

            <div class="lf_input">
                <?=
                $form->field($model, 'site')->textInput([
                    'maxLength'   => 255,
                    'placeholder' => $model->attributeLabels()['site'],
                ]);

                ?>
            </div>

            <div class="lf_input">
                <?=
                $form->field($model, 'activity_type')->dropDownList(
                    $model->getActivityTypes(),
                    [
                    'prompt' => $model->attributeLabels()['activity_type'],
                ]);

                ?>
                <span class="er_text"></span>
            </div>

            <hr class="small_hr">
            <h5>Дополнительная информация</h5>

            <?=
            $form->field($model, 'source_type')->dropDownList(
                $model->getSourceTypes(),
                [
                'prompt' => $model->attributeLabels()['source_type'],
            ]);

            ?>

            <?=
            $form->field($model, 'direction_type')->dropDownList(
                $model->getDirectionTypes(),
                [
                'prompt' => $model->attributeLabels()['direction_type'],
            ]);

            ?>

            <?=
            $form->field($model, 'comment',
                [
                'options' => [
                    'class' => 'lf_input lf_text',
                ]
            ])->textarea([
                'class'       => 'lf_input lf_text',
                'maxLength'   => 255,
                'placeholder' => $model->attributeLabels()['comment'],
            ]);

            ?>

            <div class="lf_subm">
                <input class="button" type="submit" value="Отправить">
            </div>
            <? ActiveForm::end(); ?>
        </div>

        <div id="register-distributer-step2" style="display: none">
            <div class="lf_success">
                <h2>Анкета отправлена</h2>
                <p style="text-align: center; margin: 15px 0;">Спасибо за интерес к продукту. Мы скоро свяжемся с вами.</p>
                <i></i>
                <div class="lf_subm">
                    <?=
                    Html::submitInput('Продолжить работу',
                        [
                        'class' => 'button remodal-close',
                        'data'  => [
                            'remodal-action' => 'close',
                        ],
                    ]);

                    ?>
                </div>
            </div>
        </div>
    </div>
</div>